---
format:
  pdf:
    documentclass: article
    geometry:
      - top=10mm
      - left=15mm
      - right=15mm
      - bottom=5mm
      - heightrounded
    fontfamily: libertine
    colorlinks: true
    fontsize: '16'
    include-in-header:
      text: |
        \usepackage{multicol}
        \usepackage{lipsum}
        \usepackage{hyperref}
        \usepackage{libertine}
        \pagestyle{empty}
        \setlength{\multicolsep}{2pt plus 1.0pt minus 0.75pt}% 50% of original values
        \setlength{\columnsep}{3em}
---
<!-- TITLE -->
\begin{huge}\begin{center}{\bf Montaque Reynolds}\end{center}\end{huge}

<!-- CONTACT INFO -->
\begin{center}montaque.reynolds@gmail.com ∙ \href{https://schf-org.github.io/SCHF-Org/}{Portfolio} ∙ \href{https://github.com/}{Github} ∙ \href{https://www.linkedin.com/in/alex-bass-4a7465161/}{LinkedIn}
\end{center}
\vspace{15pt}

<!-- EDUCATION: 1ST BULLET -->
\begin{large}
  {\bf EDUCATION}
  \vspace{3pt}
  \hrule
  \begin{multicols}{2}
    \begin{flushleft}{\bf Saint Louis University}\end{flushleft}
    \begin{flushright}Saint Louis, MO\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}Doctor of Philosophy: Philosophy\end{flushleft}
  \end{multicols}
\end{large}
\vspace{-0.17cm}
\begin{flushleft}Dissertation: Emotional Data and Spiritual Meaning, An analysis of the moral expression of sentiment in fiction\end{flushleft}
\vspace{-0.17cm}
\begin{flushleft}\emph{AOS:} Phil Mind, Social and Moral Epistemology\end{flushleft}

\vspace{0.05cm}

<!-- EDUCATION: 2ND BULLET -->
\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf Oklahoma State University}\end{flushleft}
    \begin{flushright}Stillwater, OK\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}Master of Arts: Philosophy\end{flushleft}
  \end{multicols}
\end{large}
\vspace{-0.17cm}
\begin{flushleft}Thesis: Evolution of Religious Belief and Naturalism: Agency, Character and Adaptation in Christian Belief\end{flushleft}
\vspace{1.5pt}

<!-- EDUCATION: 3RD BULLET -->
\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf Seattle Pacific University}\end{flushleft}
    \begin{flushright}Seattle, WA\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}Bachelor of Arts: Philosophy\end{flushleft}
  \end{multicols}
\end{large}
\vspace{1.5pt}

<!-- SKILLS -->
\begin{large}{\bf SKILLS}
  \vspace{3pt}
  \hrule
\end{large}
\vspace{-0.16cm}
**Languages and Tools** - *basic:* Python, R *intermediate:* Rmarkdown, LaTeX, Git
**Selected Coursework** - Deep Learning for Humanists (Workshop, University of Victoria), NLP / Sentiment Analysis / Corpus Linguistics, Agents and Agency (Graduate Seminar Katheryn Lindeman), CoLiPhi Corpus Linguistics and Philosophy (Workshop, University of Zurich)


<!-- EXPERIENCE : 1ST BULLET-->
\begin{large}{\bf EXPERIENCE}
  \vspace{3pt}
  \hrule
  \begin{multicols}{2}
    \begin{flushleft}{\bf \href{https://https://www.stetson.edu/artsci/philosophy/}{Stetson University}}\end{flushleft}
    \begin{flushright}Aug 2025-Present\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Visiting Assistant Professor of Philosophy}\end{flushleft}
    \begin{flushright}Deland, FL\end{flushright}\end
  {multicols}
\end{large}
\vspace{-0.16cm}
* Teach Logic, Aesthetics, Philosophy of Law, Intro to Philosophy—emphasizing reasoning, collaboration, and real-world applications.

\vspace{7pt}

<!-- EXPERIENCE : 2ND BULLET -->
\begin{large}
  \begin{multicols}{2}
  \begin{flushleft}{\bf \href{https://snorkel.ai}{Snorkel.ai}}\end{flushleft}
    \begin{flushright}Jan 2025-Present\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Expert Contributor}\end
    {flushleft}\begin{flushright}Remote\end
    {flushright}
  \end{multicols}
\end{large}
\vspace{-0.16cm}
* Authored and validated graduate-level, high-difficulty problems to test/enhance LLM reasoning, fluency, and problem-solving; contributed to proprietary datasets for AI fine-tuning, benchmarking, and reinforcement learning.
* Identified reasoning flaws in AI-generated responses, refining outputs for rigorous, verifiable solutions—directly advancing LLMs for academia, industry collaboration, and real-time decision-making.

\vspace{7pt}

<!-- EXPERIENCE : 3RD BULLET -->
\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf \href{https://schf-org.github.io/SCHF-Org/}{Saleno Center for Human Flourishing}}\end{flushleft}
    \begin{flushright}Aug 2024-Present\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Founder, Director}\end
    {flushleft}\begin{flushright}Saint Louis, MO\end
    {flushright}
  \end{multicols}
\end{large}
\vspace{-0.16cm}
* Lead SCHF project advancing human flourishing and moral well-being via interactive digital platforms (e.g., MMOs), investigating impacts on critical thinking, ethical reasoning, and moral decision-making for underserved youth.
* Developed AI-driven tools to model ethical AI interactions, aligning with productivity platforms (e.g., PhiloQuest, a DND philosophical campgaign generator) that guide users to next-best actions.

\vspace{7pt}

<!-- EXPERIENCE : 4TH BULLET -->
\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}{\bf \href{https://www.lc.edu/}{Lewis and Clark Community College}}\end{flushleft}
    \begin{flushright}August 2024 - May 2025\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
  \begin{multicols}{2}
    \begin{flushleft}\textit{Philosophy Instructor (Adjunct)}\end{flushleft}
    \begin{flushright}Godfrey, IL\end{flushright}
  \end{multicols}
\end{large}
\vspace{-0.16cm}
* Contemporary Moral Problems (Ethics): Designed courses integrating AI ethics and collaborative problem-solving.
\vspace{7pt}

<!-- PERSONAL PROJECTS : 1ST BULLET -->
\begin{large}
{\bf SELECTED PROJECTS}
  \vspace{3pt}
  \hrule
  \begin{multicols}{2}
    \begin{flushleft}\textit{\href{https://github.com/acbass49/school-shootings}{Bayesian County-Level School Shooting Analysis}}\end{flushleft}
    \begin{flushright}August 2022\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
\end{large}
* Compared and estimated several Bayesian Regression models with PYMC3 in Python. Ultimately, used **hierarchal negative binomial model** to predict shootings and make inferences about gun laws

\vspace{7pt}

<!-- PERSONAL PROJECTS : 3RD BULLET -->
\begin{large}
  \begin{multicols}{2}
    \begin{flushleft}\textit{\href{https://alexbass.me/projects/star_wars_capstone/}{Political Message Detection and Likeability in Films}}\end{flushleft}
    \begin{flushright}April 2020\end{flushright}
  \end{multicols}
  \vspace{-0.17cm}
\end{large}
* recieved award from Political Science department to fund a panel survey (n=1000).
* estimated linear regression and multinomial logit in observational study context and wrote paper \href{https://alexbass.me/projects/star_wars_capstone/Capstone%20Project.pdf}{[here]} on findings.
